name: 'healthcare_dbt_project'
version: '1.0.0'

profile: 'healthcare_dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  healthcare_dbt_project:
    dimensions:
      +materialized: view
      +schema: dimensions
    marts:
      +materialized: view
      clinical:
        +schema: clinical
      financial:
        +schema: financial
    prep:
      +materialized: ephemeral
    staging:
      +materialized: ephemeral
seeds:
  healthcare_dbt_project:
    +schema: raw
